[versions]
junit = "5.11.3"

[plugins]
shadow = "com.gradleup.shadow:8.3.5"
runPaper = "xyz.jpenilla.run-paper:2.3.1"
indra = "net.kyori.indra.git:3.1.3"
bukkitPluginYAML = "net.minecrell.plugin-yml.bukkit:0.6.0"

[libraries]
paper = "io.papermc.paper:paper-api:1.21.3-R0.1-SNAPSHOT"
triumph-cmd = "dev.triumphteam:triumph-cmd-bukkit:2.0.0-SNAPSHOT"
miniplaceholders = "io.github.miniplaceholders:miniplaceholders-api:2.3.0"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.17.2"
mongojack = "org.mongojack:mongojack:5.0.2"
junit = { module = "org.junit:junit", version.ref = "junit" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[bundles]
junit = [ "junit", "junitJupiter" ]